### ISSUE TITLE
Automatic Pinning to Toolbar

### ISSUE THREAD

**Issue by JeffJSnyder** [Le0Michine/FusionGridfinityGenerator#1]
When I unpin the bin and baseplate, close F360, then re-open F360 the tools re-pin themselves to the toolbar.  Is that a me problem or something in the script that causes that to happen?

**Comment by Le0Michine** [comment]
It looks like it was left from initial addin template, updated code to persist current value in configuration file, the issue should disappear after update. Let me know if you still experience the issue a

**Comment by JeffJSnyder** [comment]
Tested.  Issue resolved.  Thank you.
