### ISSUE TITLE
Error when collapsing or expanding sections

### ISSUE THREAD

**Issue by Cellivar** [Le0Michine/FusionGridfinityGenerator#10]
I use the default Gridfinity dimensions so I clicked the arrow at the top to collapse the "Basic Sizes" section. I got this error in a popup twice.

![image](https://user-images.githubusercontent.com/1441553/227455153-676ddf79-719c-4cf1-94ef-202d536534d4.png)

```
An unknonwn error occurred, please validate your inputs and try again:
Traceback (most recent call last):
  File "C:\git/FusionGridfinityGenerator\commands\commandCreateBin\entry.py", line 709, in command_input_changed
    if changed_input.parentCommandInput.id == BIN_COMPARTMENTS_TABLE_ID:
AttributeError: 'NoneType' object has no attribute 'id'
```

It didn't appear to affect the generation of the bins, just messed with the UI a bit.

**Comment by Le0Michine** [comment]
Hi, thanks for reporting this, I found an issue and updated the code, it should be addressed in the latest version. Also it should be able to remember collapsed state across multiple usages until you exist fusion

**Comment by Le0Michine** [comment]
Feel free to reopen if issue persists for you with the latest version

**Comment by Cellivar** [comment]
Updated and working well, thank you!
