### ISSUE TITLE
Holes slightly mis-aligned

### ISSUE THREAD

**Issue by mmmyers** [Le0Michine/FusionGridfinityGenerator#12]
Looks like the generated magnet / screw holes are just slightly misaligned. I generated a solid bin with default settings, and the holes are not the same distance from the edges.

I'm sure these will still work, but you probably want to make the magnet holes are symmetrical just to make sure the bin geometry is perfect.

![image](https://user-images.githubusercontent.com/865682/227720977-2385ed26-c0a2-4d7b-8fed-a8625a99de88.png)

**Comment by Le0Michine** [comment]
good catch, looks like I missed that when was updating logic around tolerances

**Comment by Le0Michine** [comment]
should be fixed now

![image](https://user-images.githubusercontent.com/2707008/227728639-caa6b574-3dbd-4021-992e-ba61e7058c72.png)

**Comment by Le0Michine** [comment]
feel free to reopen if the update doesn't resolve the issue for you

**Comment by mmmyers** [comment]
Thanks, I appreciate the fix, and the plugin in general! It makes it really easy to start creating custom Gridfinity modules.
