### ISSUE TITLE
Screw hole chamfers are on the bottom

### ISSUE THREAD

**Issue by Schmierer-Eng** [Le0Michine/FusionGridfinityGenerator#128]
When using the screw-hole feature the chamfer is modeled on the bottom surface. 

![image](https://github.com/user-attachments/assets/6b68d9b3-cbd5-4141-9d39-54ff9e91511b)

**Comment by Le0Michine** [comment]
Hi, thanks for the report, could you clarify what is the issue and what’s the expected behaviour?

Chamfers on the bottom are following the original design. I believe the intention there was to screw bins to the plates.

**Comment by Schmierer-Eng** [comment]
Ok that make sense. I was under the belief that you would want to take the bins off the grids therefore the screws would be to attach the grid to something like a desk but if the original intention was to screw the box's to the grid then there is no issue, thanks.

________________________________
