### ISSUE TITLE
Feature Request: Add option for 3-tiered supportless counterbore holes

### ISSUE THREAD

**Issue by mmmyers** [Le0Michine/FusionGridfinityGenerator#13]
Could you change to the 3-tiered counterbore holes, instead of the 2-tiered one, or make it able to change the style as an option in the creation option? Here's a picture of the type of change I mean.

![image](https://user-images.githubusercontent.com/865682/227737161-aafc9a22-c65a-4e3f-878d-d9cc65c66979.png)

For whatever reason, on my printer, the 3-tiered ones print a lot better. Here's an example of the 2-tiered ones in the current plugin on the left, and 3-tiered ones afterwards:

2-tiered hole: 
![image](https://user-images.githubusercontent.com/865682/227737254-794c82e7-bfe4-4aa0-8821-a12509f549fc.png)

3-tiered hole: 
![image](https://user-images.githubusercontent.com/865682/227737289-e26b8749-aa84-4d7e-9d15-341881365c07.png)

**Comment by Le0Michine** [comment]
thanks for your feedback, I'll try to experiment with that

**Comment by mmmyers** [comment]
I decided to go and learn the F360 Python API and do it myself. I created a pull-request for you.

Hope it helps. I've already found this project useful, so I figured I could contribute a feature that would be helpful for me.

**Comment by Le0Michine** [comment]
haha, I was working on exactly that this morning

**Comment by mmmyers** [comment]
Sorry, I probably should have told you I decided to try my hand at it myself. Haha.

**Comment by Le0Michine** [comment]
thanks for the PR, I appreciate that, and I'm sorry I changed the code quite a bit so it seems unmergeable now

**Comment by Le0Michine** [comment]
I simplified the way the groove is created, let me know if you get a chance top test that

**Comment by mmmyers** [comment]
I just tested out your update. Works for me! Thank you very much.
