### ISSUE TITLE
Label tabs with shelled bins

### ISSUE THREAD

**Issue by HelgeBoe** [Le0Michine/FusionGridfinityGenerator#15]
First of all thanks for sharing your great add-in - very much appreciated!!

I really like a lot the shelled body as I reduces significantly printing time, but unfortunately it seems that the combination of a label with a shelled bin is not supported, or I am missing something?

What I did: 
1. Create a 1x3x6 hollow bin with label -> bin is created as expected
2. Change bin type from hollow to shelled, all other parameters remain the same -> bin without a label tab is created

**Comment by hany** [comment]
I'm experiencing the same issue. Adding a scoop or multiple compartments when using the "Shelled" body type results in a simple shelled body with none of the features applied.

**Comment by Le0Michine** [comment]
Hi, thanks for your feedback. Unfortunately, because of the way shelled bin is created adding regular bin features is complicated. I might be able to add the tab as it probably should work, however scoop and compartments would be challenging as they are created as negative volumes which are subtracted from the bin body

**Comment by Le0Michine** [comment]
There maybe a way though not sure how well it would work 🤔

**Comment by ansgarhimmel** [comment]
+1
I'd also be really interested in having labels on shelled bins. In fact, trying to create such bins was my initial reason for installing this very cool plugin :-)

**Comment by Le0Michine** [comment]
seems like the easiest way to support tabs for shelled bins is to use the same solid prism body, so technically those won't be shelled like the rest of the bin. It seems like it might be possible to get shelled tab on the outer wall but to do it for all walls seems like a significant challenge right now.
I might be able to add regular tabs and compartments to shelled bins, but not sure if I will be able to do properly shelled tabs any time soon

**Comment by ansgarhimmel** [comment]
> I might be able to add regular tabs and compartments to shelled bins, but not sure if I will be able to do properly shelled tabs any time soon

At least for my use case, regular tabs would be perfectly fine. In my mind, the "shelled" vs. "hollow" property relates only to how the bottom of the bin is created; maybe I'm running contrary to the initial design intention there(?)

**Comment by ttsai** [comment]
I would also like to +1 for this feature.  I found another model that does labels and dividers for shell bins.  However, the plugin nature of your model is much more elegant. 

https://www.printables.com/model/353224-gridfinity-lite-ultra-blocks-template

**Comment by Le0Michine** [comment]
added a simple implementation of label tab for shelled bins, it basically replicates the approach for regular bins

**Comment by Le0Michine** [comment]
the change is added into new release https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.7.0, pending update of the app in the autodesk app store
