### ISSUE TITLE
Bin label tab width smaller than input value

### ISSUE THREAD

**Issue by granthworth** [Le0Michine/FusionGridfinityGenerator#16]
Loving this tool! I have an issue when making labeled bins where the actual flat surface for the label is narrower than the tab width I enter. For instance, if I enter 13mm, the outer most label tab is 10.76xx mm and the tabs for the interior rows of a divided bin are 11.76xx mm. So, to get tabs that are wide enough for a 1/2" or 12.7mm label, I have to enter 15mm.

Small issue for the usefulness of your tool, but I thought I would bring it to your attention nonetheless. Thanks for your hard work!

**Comment by Le0Michine** [comment]
the tab width is measured from the inner wall surface it is attached to. Part of that width get's eaten by 0.6mm fillet

for example when I enter 15mm as you can see on the screenshots the generated tab width is 15mm if we remove the fillet. For tabs attached to internal compartment walls you also get extra 1.2mm of that wall thickness.

![image](https://user-images.githubusercontent.com/2707008/231296270-fee42f18-bb22-45ac-98fa-3da2da6b0928.png)

![image](https://user-images.githubusercontent.com/2707008/231296319-d1e4cd00-d363-47be-99cb-f06d33c4be1f.png)

**Comment by Le0Michine** [comment]
updated the way tab width is used, it is still measured from the wall surface but should account for the fillet

![image](https://user-images.githubusercontent.com/2707008/231302434-cc757826-9097-4380-90b9-95a71bec7f55.png)

**Comment by Le0Michine** [comment]
feel free to reopen if you still face the issue
