### ISSUE TITLE
Feature request Generate base based off of external measurement 

### ISSUE THREAD

**Issue by swissvinnie** [Le0Michine/FusionGridfinityGenerator#19]
New here. so please forgive any discretions. 

Came here after some searching for how to make a parametric model for gridfinity base plates. 

My Idea would be: " I want to add gridfinity to my drawer" Take some measurements. 
Open F360 and add the dimensions of my drawer. 

And it would adjust the number of cells to fit evenly.  It would then make up any gaps by increasing the thickness of the outermost wall, split evenly from left to right, and top to bottom. 

then say my printer can only print 5x5 cells max, enter that and it would split the model into printable components. 

Just an Ideal. 

Cheers. 

swissvinnie

**Comment by Whitespace** [comment]
NB: If a dimension were—say—5.8 cells wide, then your algorithm could generate wall thicknesses of 16mm+, which would be very chonky.

I did something like this recently that had a different algorithm. I had a moveable cart with three curved bins—similar to an Ikea RÅSHULT. I generated a larger baseplate than I could fit and then intersected it with the dimensions of the cart bins, leaving me with partial base edges that fit nicely against the walls of the cart. I had a few of these carts so it made sense to iterate on a snug solution vs using the other recommendations:

- mounting putty (blue tak)
- hot glue
- double-sided tape
- shove something in the sides.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/3590/233970520-aa1f5d87-2ab2-4ae9-b27b-1c4192309bd8.png">

![PXL_20230424_102813538](https://user-images.githubusercontent.com/3590/233970969-6668111f-7cbe-49b6-ad43-6cd092197c0b.jpg)

**Comment by Le0Michine** [comment]
this will be somewhat addressed in the new version which adds extra padding to the baseplate sides, it might still require to do some extra cuts on the sides to be able to nicely fit into the ikea cart on the photos

<img width="826" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/c06f2b2c-f880-4d0e-b431-41d625a80111">
