### ISSUE TITLE
Enhancement Request - Ability to print magnets into the magnet holes of the bins.

### ISSUE THREAD

**Issue by ZeroNull42** [Le0Michine/FusionGridfinityGenerator#2]
Add the ability to enable printing magnets into the bin magnet holes where you add the option to add a 1st layer of .2 mm solid layer covering the holes so I can then put a pause at layer 12 or so to place the magnets in the holes and then resume printing.  Right now, I manually do this and would be incredible to have this be an enhancement.  Also, could add this feature to the base plates as well.

**Comment by matthewethomas** [comment]
Concur on this request - it's a major PIA to glue magnets in after the fact for both the bins and baseplates. If we could just print them in-place it would save so much time and effort

**Comment by geekifier** [comment]
I found that I can simply make the hole diameter match the magnet diameter (nominal 6.0 mm), and the magnet simply friction fit snugly into the holes. No glue needed. You can use a square drive bit to help set the magnets into the holes.

**Comment by Le0Michine** [comment]
@ZeroNull42 just wanted to double check, does the press fit option solve the issue of inserting magnets for you or is there something making it not viable for your use case?

**Comment by Le0Michine** [comment]
resolving due to lack of activity, feel free to reopen if needed

**Comment by ZeroNull42** [comment]
> 

I just like the ability to print the magnets into the holes.  This would be really cool if you could implement.  Press to fit does not work all the time due to magnets size tolerances are not always good.
