### ISSUE TITLE
Base interface features don't take basic sizes into account

### ISSUE THREAD

**Issue by tnoppeney** [Le0Michine/FusionGridfinityGenerator#21]
Hi,

I want to create bins with a base size 36x36mm and magnet holes, but those do not consider the dimensions and seem to be placed as if the bin was still 42x42mm in size:

![grafik](https://user-images.githubusercontent.com/10694722/233835520-bbb4ac4f-0193-4d52-a7e4-52c037737dac.png)

**Comment by Le0Michine** [comment]
that's a limitation which was there from the start, need to figure out a proper way to generate those sockets. Maybe specifying offset or distance between when would be useful.

Could you share your expectations for how this part is supposed to work? Do you want to have completely custom grid size with your own socket spacing? Or are you trying to create something somewhat backwards compatible?

**Comment by tnoppeney** [comment]
My expectation was that the sockets would maintain their distance from the edge no matter what the size was set to.

**Comment by Le0Michine** [comment]
thanks for the update, I'll take a look once I have some time, probably shouldn't be too hard to add 🤔

**Comment by Le0Michine** [comment]
Updated the way holes position is calculated, now it is counted from the bin side so it should scale to some degree for smaller bins better

<img width="1031" alt="Screenshot 2023-07-03 at 12 13 21" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/904b7fee-19d9-4e99-8126-c5c763d9e317">

**Comment by Le0Michine** [comment]
that includes baseplates 

<img width="695" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/b5094f9d-0a8d-43c1-a6fb-5c5d08d23def">

**Comment by Le0Michine** [comment]
unfortunately it won't work as well with half width bins 

<img width="821" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/4446d856-6a7b-4541-af42-b9d8676f414c">


But it is possible to partially suppress pattern feature to get holes only on one side so they still could be compatible with standard baseplates 

<img width="789" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/fcf86578-3d6b-485f-a4a5-58a777f7ec8f">

<img width="778" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/2315252a-4b7c-457e-a42d-d8febc69cdd6">

**Comment by Le0Michine** [comment]
because it is an old issue I'm gonna close it for now, feel free to reopen if you still run into problems with it or create a new one
