### ISSUE TITLE
Plugin doesn't work on MacOS (Doesn't appear in dropdown)

### ISSUE THREAD

**Issue by edddeduck** [Le0Michine/FusionGridfinityGenerator#23]
When following the install instructions on MacOS the plugin doesn't appear in the drop down. You can install it and press run (and you see no errors) but nothing appears in the app.

Happy to provide logs etc if you tell me how to get them.

**Comment by edddeduck** [comment]
Tested using M2 MacBookPro using MacOS 13.2.1

**Comment by therick0996** [comment]
works fine for me. M1 Pro macOS 13.3.1

**Comment by LandonSchropp** [comment]
This works fine for me as well on an M1 MacBook Pro.

**Comment by azcoov** [comment]
Worked great for me: iMac Pro 2017 Ventura 13.2.1

**Comment by Le0Michine** [comment]
Hi, this kind of issue tends to an issue during installing the addin, please validate these
- the path to addin should be specified to the location containing GridfinityGenerator.manifest file
- all files from the repository should be in that folder with structure unchanged

**Comment by deivuh** [comment]
I'm experiencing the same issue.  The options don't show up for me even tho it does show up on the add-ins list and does run with no issue. 

MacOS 13.3.1 (22E261), M1 Pro. 
Fusion 360 2.0.16009 x86_64 [Rosetta 2] Personal Edition

**Comment by deivuh** [comment]
An update here, I noticed that I was adding this the wrong way by using the `Create` button in the add-ins window. I realized that there's the green `+` button, selected the Fusion Gridfinity Generator folder and viola, it shows up now. 

@edddeduck Try this out, you were probably doing it the same way as a I did. 

@Le0Michine Thank you for such a useful generator :)

**Comment by edddeduck** [comment]
> An update here, I noticed that I was adding this the wrong way by using the `Create` button in the add-ins window. I realized that there's the green `+` button, selected the Fusion Gridfinity Generator folder and viola, it shows up now. ![image](https://user-images.githubusercontent.com/1679010/237124197-468f4b3e-947e-4cc4-a2b8-c2b8caf9a3cb.png)
> 
> @edddeduck Try this out, you were probably doing it the same way as a I did.
> 
> @Le0Michine Thank you for such a useful generator :)

Thanks I was about to post here and report the same thing, that plus didn't look like a clickable icon (offset and not looking like an intractable object) so I figured the Mac UI had altered in some way.

If useful I'd be open to providing a pull request to update the instructions for people like me who perhaps didn't pay enough attention / got confused with Fusion 360's interesting UX decisions.

**Comment by Le0Michine** [comment]
yes, it seems like it makes sense to add some graphics to the installation manual. Still hoping I can get this packed into self installing .msi/.pkg package at some point to mitigate this altogether

**Comment by deivuh** [comment]
I think specifying that part of the process (the + button) in the readme file should be enough.
