### ISSUE TITLE
feature request: add arrows next to Main Dimensions

### ISSUE THREAD

**Issue by therick0996** [Le0Michine/FusionGridfinityGenerator#28]
Would be nice to have arrows to quickly increase/decrease the main dimensions of the bins, similar to the bin compartments

![Screenshot 2023-05-12 at 8 19 43 AM](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/40247140/7eb72b00-99c1-4992-862d-c9fb942085ab)

**Comment by Le0Michine** [comment]
will update for width and length. For height it might be still useful sometimes
