### ISSUE TITLE
MSI installer crashes

### ISSUE THREAD

**Issue by solidus0079** [Le0Michine/FusionGridfinityGenerator#30]
Hi, both the 1.0 and x.10 versions crash the MSI installer on my machine.  Attached is MSI log for the x.10 version install.  If the issue is on my end I have no idea.  Thought you should know at any rate.  :-)
[MSI19238.LOG](https://github.com/Le0Michine/FusionGridfinityGenerator/files/11713370/MSI19238.LOG)

**Comment by Le0Michine** [comment]
Hi, I'll be publishing installers through autodesk app store, it should work better https://apps.autodesk.com/FUSION/en/Detail/Index?id=7197558650811789
