### ISSUE TITLE
Feature Request: option for connection whole

### ISSUE THREAD

**Issue by m1stborn** [Le0Michine/FusionGridfinityGenerator#33]
Hey,

Just found this repo a couple of days ago, this is such excellent work!
Can you add an option that only adds connection whole at the most outside edge? As the red edges in the below sketch.
This would be super convenient.

Cheers!

![Gridfinity generator request (1)](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/31998417/e7708327-07db-4eaa-8686-0610691ab9a2)

**Comment by Le0Michine** [comment]
the change is made, will add it into the next release
