### ISSUE TITLE
Add option for magnet mounts on bottom of baseplates (or at least counter bore screw holes)

### ISSUE THREAD

**Issue by PogopunkXIII** [Le0Michine/FusionGridfinityGenerator#34]
I'm trying to make some baseplates for my toolbox, and my original idea was to put magnets on the _under side_ of the baseplates so the baseplates were still removable but would stick to the toolbox drawer.

unfortunately when adding screw holes they're counter sunk which means I'll need to drill them out if I want to put magnets on the under side of the baseplate, not a huge deal but it would be awesome if I could choose to put magnet holes on the bottom, or at the very least change the screw holes to be counter bore instead of counter sunk, which effectively solves the problem.

I realize that printing holes like this will result in the holes being bridged, or need supports but I think for the sake of mounting magnets I'm ok with the print quality inside the holes to be not perfect.

**Comment by PogopunkXIII** [comment]
I started pawing through the code a little, I might try to do this myself and make a PR next week.

**Comment by robi000001** [comment]
I simply used 3x3 mm cylindrical press-fitted magnets and set the bottom thickness to 3 mm. This way the magnets can be reached from both the top and the bottom side of the baseplate.
![Képernyőkép 2023-07-18 212717](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/51284809/ed5310df-1d47-4b82-a912-518c4eb35fa1)

**Comment by PogopunkXIII** [comment]
That is pretty clever, I'll do that.
