### ISSUE TITLE
Gridfinity bin - Bin wall thickness cannot be 2.1 mm and greater 

### ISSUE THREAD

**Issue by amra** [Le0Michine/FusionGridfinityGenerator#35]
When I set bin wall thickness to `2.1 mm` the field will be grayed out, and it's not possible to click `Ok` to generate the object.

# Set to `2.1 mm`
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/174620/b3c680ec-27b5-486e-8ec3-f84a40be9127)

# Set to `2.0 mm`
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/174620/d680960c-d803-475a-ba70-3b86244065a8)

**Comment by Le0Michine** [comment]
Hi, thanks for opening an issue.
There are some limits for values which are supported to ensure the result is predictable, so this is by design. 
Is there a particular reason why you are trying to get walls so thick?

**Comment by amra** [comment]
Not really. 
I put there a value and then I was not able to click ok. I didn't expect that and spent 15 minutes searching for the cause.

**Comment by amra** [comment]
Is it possible to limit the range of values in the dialog?

**Comment by SuperTango** [comment]
@Le0Michine Just wondering what are the issues with wall thicknesses bigger than 2.0mm?  I'm making some 2x4u (42mm width and length unit) bins with a 14u (7mm height unit) height for some large nuts and bolts in a scenario where the bins are getting jostled around some.  The 2.0mm walls are decent but a 3.0 wall would be quite a bit stronger.

**Comment by Le0Michine** [comment]
as far as I recall it might break the bin in some combinations with other settings, don't remember what exactly happens. And there was no ask for supporting thicker walls so the limit was put at the number which doesn't seem to cause issues
