### ISSUE TITLE
Generation of gridfinity object is one entry in timeline

### ISSUE THREAD

**Issue by amra** [Le0Michine/FusionGridfinityGenerator#36]
After generating a gridfinity object about 20 operations will be added to timeline.
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/174620/cc8eba28-39eb-4652-b706-f57029bf5dbf)

Similar to other Fusion 360 operations, I would prefer this to be a single object. 
And after double-click on the operation in timeline an initial window is shown, where I can adjust parameters (e.g. edit height).

**Comment by Le0Michine** [comment]
to clarify, is the interaction you suggesting something you saw implemented by some other application? Would be great to be able to take a look at how it works.
From what I saw in the documentation so far I'm not sure that it is something supported out of the box and trying to simulate that might take a lot of effort with unstable result which would be more frustrating to use than beneficial.

**Comment by DraconPern** [comment]
For the OP, you can use the component feature and reference it externally. https://help.autodesk.com/view/fusion360/ENU/?guid=GUID-5966BF6B-4135-49B3-B5BF-29A6577C9E72 Just save the gridfinity object in it's own file and you'll not see the timeline.

**Comment by Le0Michine** [comment]
made a change automatically collapsing all generated features in timeline, will include it in the next release


![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/d5a72fcd-2007-4cf3-9c3f-27361b788926)

**Comment by Le0Michine** [comment]
the change is added into new release https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.2.7.0, pending update of the app in the autodesk app store
