### ISSUE TITLE
Option to save defaults

### ISSUE THREAD

**Issue by matt-sorenson** [Le0Michine/FusionGridfinityGenerator#47]
It'd be really nice to have an option to save defaults, ie `Generate lib for stackability` on or off, or whether screw holes/magnet cutouts are on.

**Comment by jtbrough** [comment]
Agreed. We know what our typical configuration is - the magnets we own, the system we are building and scaling. Being able to set defaults, even if just modifying some underlying json config or whatever would be lovely.
This is such an impossibly useful tool already, love using it.

**Comment by t-makaro** [comment]
On Windows, you can modify ```%appdata%\Roaming\Autodesk\ApplicationPlugins\GridfinityGenerator.bundle\Contents\lib\gridfinityUtils\const.py``` to modify values for both bins and baseplates.

Or, the ```def defaultUiState():``` function in ```%appdata%\Roaming\Autodesk\ApplicationPlugins\GridfinityGenerator.bundle\Contents\commands\commandCreateBin\entry.py``` for just bins.

Or, the ```def command_created(args: adsk.core.CommandCreatedEventArgs):``` function in ```%appdata%\Roaming\Autodesk\ApplicationPlugins\GridfinityGenerator.bundle\Contents\commands\commandCreateBaseplate\entry.py``` for just baseplates. That one looks more annoying to adjust. So if you want different values for baseplates and bins set the first file for both, and then override for bins in the second file, but a json file that lets you adjust bins and baseplates separately would be nice.

**Comment by t-makaro** [comment]
Oooh. Parameter sets would be nice. OpenSCAD does this, and it's nice when I use gridfinity rebuilt in OpenSCAD.

**Comment by Le0Michine** [comment]
persisting default settings is in progress, ability to import/export settings externally is a whole different problem, but it might be added eventually

**Comment by Le0Michine** [comment]
was implemented as part of v1.3.1.0 release. Now new defaults can be persisted and restored when fusion is reopened
