### ISSUE TITLE
Hexagon bin wall pattern

### ISSUE THREAD

**Issue by bjw-s** [Le0Michine/FusionGridfinityGenerator#48]
Hi, thanks so much for creating this Fusion plugin! It really makes creating Gridfinity boxes/bins/plates soo much easier!

One feature request that popped in my head would be the option to have hollow bins generated with a honeycomb wall pattern, similar to these bins: https://www.printables.com/model/573917-hex-bin-gridfinity-1x2

I wish I was able to add this feature myself but my CAD/Fusion skills are severely lacking. I'd more than gladly support your work with multiple coffees though :)

**Comment by jordanlambrecht** [comment]
This would be amazing

**Comment by Le0Michine** [comment]
Hi, thanks for taking the time opening the request. Unfortunately given the time available I'm not planning on implementing this level of customisation as it steps quite far away from the core idea and doesn't seem to be at the top of the most requested features
