### ISSUE TITLE
Default Settings Executes Errors

### ISSUE THREAD

**Issue by ten-tjc** [Le0Michine/FusionGridfinityGenerator#60]
Not sure what i can do to fix this but i try to create a default bin (Create / Gridfinity bin) and receive and error. Any help would be appreciated.
<img width="340" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/46502798/e1fa0ec3-3eab-4bfe-8091-d124febf8e76">

**Comment by Le0Michine** [comment]
Hi, thanks for reporting the issue. Could you provide more details about your environment?
- version of plugin
- version of fusion
- version of OS
it would also be helpful if you could post exact configuration you are using to create your bin

**Comment by ten-tjc** [comment]
Thank you for the support

1. Version of Plugin: 1.2.7.0
2. Version of Fusion: Fusion 360 2.0.17721 x86_64 [Native]
3. Version of OS: macOS 14.1.2

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/46502798/d47fb388-1702-4b2e-8ef4-a0dade21aed1)
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/46502798/fc52cd76-63d3-49d0-9fba-c0ad27bec838)

**Comment by rj-040** [comment]
Hello,
Just for reference, I run a similar setup, and do not have any problems.


    Version of Plugin: 1.2.7.0
    Version of Fusion: Fusion 360 2.0.17954 arm64 [Native] 
    Version of OS: macOS 14.1.2


![Xnip-06-Dec-08 28](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/89969184/7deb69a6-325f-405b-b36a-3701b87b7522)

**Comment by Le0Michine** [comment]
haven't had a chance to test it, but it might have something to do with inches used as a unit. Not sure if plugin can handle that correctly, would need to check

**Comment by Le0Michine** [comment]
okay then, seems like there is a bug with processing inputs then. Looks like it's not blocking at this point, will try take a look when I get some time

**Comment by nostahl** [comment]
I got same issue on osx here too just installed and tried the addin

**Comment by nostahl** [comment]
any news on this?

**Comment by nostahl** [comment]
im already on mm and experiencing the issue

**Comment by rj-040** [comment]
I'm not the developer. I'm just a user. But as you see above, it works fine for me.
Tested again just now.

These are my versions:
Fusion 360 2.0.17954 arm64 [Native] 
Active Plan: Personal
macOS 14.2.1 (23C71)

I can create the bin and the baseplates just fine.
![Xnip-30-Dec-19 31](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/89969184/77118390-bb70-409e-84d6-31c8432897fc)

**Comment by nostahl** [comment]
im on Intel Mac wonder if that's the difference here

**Comment by nostahl** [comment]
hey I figured it out haha.. I was not on a timeline enabled document... so the FIX is make sure your timeline is enabled.

**Comment by Le0Michine** [comment]
that’s interesting, probably auto grouping at the end fails
