### ISSUE TITLE
The Light base plate height should be 4.65mm instead of 4.25mm

### ISSUE THREAD

**Issue by GCheung55** [Le0Michine/FusionGridfinityGenerator#66]
According to https://gridfinity.xyz/specification, the baseplate is ~5mm or precisely 4.65mm.

[Zach's thin baseplate](https://than.gs/m/60721) looks to be exactly 5mm.

The generated Light base plate is 4.25mm. Is there an option to modify the height when generating the Light base plate?

**Comment by GCheung55** [comment]
I’d like to add that someone [created 2D drawings](https://github.com/julie777/Gridfinity/blob/main/Gridfinity%20Grid%202D%20Drawing.pdf) from Zach’s original design, that adds up to 4.65mm.

**Comment by GCheung55** [comment]
Regarding `flatten top side`, I've learned that's configurable under "Advanced plate size options" > "Clearance between baseplate and bin". Changing that to 0.10mm gives me 4.65mm. 🤦 .

Still not sure how to address the corner radius though - I'd love to understand how to fix this in general though.

**Comment by Le0Michine** [comment]
As I recall the top cut was added to avoid too narrow top which was sometimes causing slicing issues where it would generate couple extra layer of small peaks on the intersections while the lines would be considered too narrow to print and ignored for the top couple layers.

Fillet misalignment seems to be caused by the way the baseplate slots are formed, the plugin subtracts actual base pieces with thickened shell around them. Thickening occurs along a vector normal to the surface which is at 45 degree for overhanging part casing a slight mismatch. Need to do some research to figure out the correct way to address it.

**Comment by GCheung55** [comment]
Re: Top cut
Thanks for clarifying about the top cut, @Le0Michine. I didn't get slicing issues when the top was narrow, however using a 0.4 nozzle with a narrow top made the top layer too thin and, thus, terrible adhesion - the top layer was easy to delaminate. So, having the top cut is helpful.

What would you suggest to have a 4.65mm height for the light base plate, while keeping the top cut? 

Re: Fillet misalignment
I see what you mean, the inner and outer radius are not concentric when the thickened shell subtracts pieces. Would it make sense to make a copy where it has a slightly different angle to compensate for the distance, scale, and then combine instead of thicken?

**Comment by GCheung55** [comment]
I experimented with extruding the top surface or bottom surface by .4mm after the top cut, keeping the default options to produce a 4.65mm height plate. From 3D printing out the two, the bottom seems like it would be better in terms of fit. 

Extruding the top doesn’t support the bin so the bin’s bottom basically falls through the bottom opening, however, extruding from the bottom adds just enough space so the bottom of the bin is almost flush.

Here’s an image of the bottom of the plate where I’ve extruded the top by .4mm. The bin falls through the plate.
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/46033/c00c7e26-8f46-4716-afe1-b8818b8e65c3)

Here’s an image of the bottom of the plate where I’ve extruded the bottom by .4mm. The bin falls through less, almost flush.
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/46033/77804bd1-0f3d-44b0-9697-329eb18deb4b)

Re: Fillet misalignment
While printing the prototypes with extruded .4mm, it seems the corners flares out a little and could cause adjacent frames from sitting flush against each other. Maybe it’s just my print speed and filament, but I wonder if the fillet issue is somehow a variable that’s a part of the issue.

**Comment by Le0Michine** [comment]
v1.4.0.0 was released, it addresses the issue
