### ISSUE TITLE
Getting an error now after downloading latest version

### ISSUE THREAD

**Issue by ZeroNull42** [Le0Michine/FusionGridfinityGenerator#7]
Getting an error now trying to create a bin after downloading latest version see image

![image](https://user-images.githubusercontent.com/25206049/226004136-ce63704c-f44c-4902-b1bf-bfff4db8290b.png)

**Comment by ZeroNull42** [comment]
Looks like I figured out how to fix my error.  Go to the ? icon in the upper right corner, select Service support and diagnostics, then select Utility Menu.  On the popup dialog click Repair Fusion 360.  I was then able to create Bins and baseplates.

**Comment by ZeroNull42** [comment]
Looks like I figured out how to fix my error.  Go to the ? icon in the upper right corner, select Service support and diagnostics, then select Utility Menu.  On the popup dialog click Repair Fusion 360.  I was then able to create Bins and baseplates.

**Comment by Le0Michine** [comment]
Hi, I'm sorry you got an issue there. I pushed a few updates in the past couple days and when I'm trying to reproduce with the same inputs it works on my end. Could you try to update and confirm if that's still an issue?

![image](https://user-images.githubusercontent.com/2707008/226240341-b75618f6-d108-41a5-9b58-17e7a045bf0d.png)

**Comment by kevincali** [comment]
I just ran into the same issues with the latest master branch.
Repairing Fusion360 also fixed it for me

**Comment by kevincali** [comment]
I'm running `Windows 10 Pro 22H2 (22621.1413)` with `Fusion 360 2.0.15509 x86_64`.
The fusion version seems to be the most up2date one as of today.

It could be, that the repair step involves an update. 
This would explain why it works after repairing🙂
