### ISSUE TITLE
Wish: Naming for Sketches and Construction Planes

### ISSUE THREAD

**Issue by oni-23** [Le0Michine/FusionGridfinityGenerator#73]
Hi,

thanks for your great add-in! It will help me a lot!

I'd love to see a naming for the sketches and planes, that I can learn from the created object. (I'm new to Fusion, coming from a background of 3D software.)
![Screenshot 2024-01-05 234721](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/93731791/302f5f45-828b-4070-99dd-401a96aa5681)

**Comment by Le0Michine** [comment]
Hi, this is something I'm trying to do as I work on some other things or fixing issues. Currently, I don't have plan for naming everything in one go, though I would be open for a pull request.
