### ISSUE TITLE
MacOS Addin installs but is not visible

### ISSUE THREAD

**Issue by Jeggo65** [Le0Michine/FusionGridfinityGenerator#75]
I am using Fusion360 on a Mac

Fusion 360 2.0.17954 x86_64 [Native] 
macOS 14.2.1 (23C71) on Macmini8,1

Your add in (v 1.2.7.0) installs without any issues and shows up at the file location you mention in the help for uninstall.
 There is an other add in already installed, which runs as it should be.

I already started Fusion several times, changed the Fusion language from German to English and did several uninstalls.
No success so far. What could I check/do?

CU

Jens

**Comment by maurbano** [comment]
I had the same issue and after some research I found this to be a permissions issue. This article on Autodesk's site solved my problem:
[https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/Add-ins-installed-on-Mac-do-not-show-up-in-the-Autodesk-Fusion-add-in-dialog.html](url)

**Comment by Jeggo65** [comment]
Thanks for the hint, but it did not work. I toggled the access rights from rw to r and back. The access right of the ApplicationPlugins folder are OK, as an other plugin is running and the Gridfinity Generator also shows up.
There was no success.
What solved the problem was installing it from the terminal with these command:
sudo installer -pkg /path/to/package.pkg -target /
