### ISSUE TITLE
rectangular baseplate ???

### ISSUE THREAD

**Issue by muppy** [Le0Michine/FusionGridfinityGenerator#76]
I see that bin generation allows to specify both base width and length, allowing for different values of width and length. It is not the same for generation of grid, where you can specify only the base width, the lenght will be equal to the width.
It would be useful if allow to set both width and length also for the grid.
Thank you
Andrea

**Comment by Le0Michine** [comment]
coming soon :) 

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/120915e8-4098-45b3-ae9d-36da03987b8d)

**Comment by muppy** [comment]
That's great!!

**Comment by Le0Michine** [comment]
this is included into [v1.3.1.0](https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.3.1.0), available for direct download and will get published in the autodesk appstore soon
