### ISSUE TITLE
"Tool Body Error" when adding label to bin

### ISSUE THREAD

**Issue by scriptnugget** [Le0Michine/FusionGridfinityGenerator#78]
I noticed that an error appears when adding a label to a bin. "Combine 7" gives a "Tool Body Error" saying that a tool body is lost. It does not seem to influence the final bin model that is produced, but there might be something going wrong or some feature missing.

Plugin version: latest, 1.2.7 freshly installed
Fusion 360 version: 2.0.18203 arm64
OS: macOS Sonoma 14.2.1
Python 3.12

Plugin settings tested: fully default, only checked the "Add label"-box

<img width="466" alt="Screenshot 2024-01-23 at 12 57 33" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/b3162bb4-02ec-4728-99a5-10479956dd92">

^"Review Error" info screen

<img width="697" alt="Screenshot 2024-01-23 at 12 57 54" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/45875510/ce89d8a2-673d-45e4-bcc8-4061d3353b39">

^Produced 2x3 model, consisting of a single body so the end result is fine.

**Comment by Le0Michine** [comment]
this is addressed in [v1.3.1.0](https://github.com/Le0Michine/FusionGridfinityGenerator/releases/tag/v1.3.1.0), currently available for direct download and will be published in autodesk store soon
