### ISSUE TITLE
Feature request - Add the ability for dividers

### ISSUE THREAD

**Issue by ZeroNull42** [Le0Michine/FusionGridfinityGenerator#8]
Add a feature that will allow you to configure bins to have any number of dividers and direction i.e. width or depth wise.

**Comment by Le0Michine** [comment]
Hi, that's actually is in progress, initial version is available today, it adds an option to generate compartments in uniform grid or allows you to configure which cells to cut/merge. Let me know if that's what you were looking for. Here is couple examples of what can be generated now

![](https://raw.githubusercontent.com/Le0Michine/FusionGridfinityGenerator/master/documentation/assets/bin-custom-compartments-variant-b-options.png)
![](https://raw.githubusercontent.com/Le0Michine/FusionGridfinityGenerator/master/documentation/assets/bin-custom-compartments-variant-b.png)

![](https://raw.githubusercontent.com/Le0Michine/FusionGridfinityGenerator/master/documentation/assets/bin-uniform-compartments-options.png)
![](https://raw.githubusercontent.com/Le0Michine/FusionGridfinityGenerator/master/documentation/assets/bin-uniform-compartments.png)

**Comment by gillesguillemin** [comment]
Awesome 👍

**Comment by sdlafferty** [comment]
This is awesome, thanks.

Would there be the possibility of adding the ability to define different depths for each compartment (i.e. raise the bottom of that compartment)?

**Comment by gillesguillemin** [comment]
> This is awesome, thanks.
> 
> Would there be the possibility of adding the ability to define different depths for each compartment (i.e. raise the bottom of that compartment)?

Actually +1 on this suggestion. I had thought about the same thing when playing with the new functionality.

**Comment by gillesguillemin** [comment]
Imagine a 3x2 bin of say 6u height, split in 2 lengthwise, with the right compartment full depth to store blocs of post-its sideways, and the left compartment only half (or 1/3) depth to store pens.

It could be done with 2 separate bins for sure, but those clearly go together so why not build something like that.

First thing that pops to mind though, I’m sure there are plenty of other scenarios like that.

**Comment by sdlafferty** [comment]
My use case so far would be for a 2x2 bin that is split into four compartments. This will be storing scissors, knives, and similar sharp items. Some of these items are smaller, so I want to raise the base of one of the compartments so that the small items in there are still easily accessible, and keeping all these items together.

**Comment by asanjabi** [comment]
I had a similar use case.  Was able to get it done using the Press Pull tool, which I found intuitive than doing it at create time, since you can adjust as needed.

**Comment by Le0Michine** [comment]
are you thinking of it more as compartment depth measured from the top or a bottom raise measured from the bottom? I'm also thinking about what units would be best to use there and so far seems like mm would be the easiest way because compartment width and length is already expressed in sort of compartment grid units so I probably wouldn't necessarily want to mix it with height units unless it makes things more convenient comparing to mm

**Comment by sdlafferty** [comment]
I think mm would work best. 

I also think that either option for depth would work (maybe give user the option to switch between depth from top or raise amount?). Would probably just be simplest to have it as a bottom raise offset value 

I can also see a use case where someone may want to raise the bottom of all compartments the same amount, to either raise up all compartments if the bin might be behind other objects on a desk, or to increase the distance from the base to the comportment bottoms for additional modifications after the initial creation, maybe cutting a hole in the bin from one side between the base and the compartment bottoms for storage or to run power cables into the compartments.

**Comment by Le0Michine** [comment]
so I got a version with mm and depth working. I realized that I have no idea what to call that parameter if it is measured from the bottom (one word so it would be obvious what it is). Also added a few quality of life improvements
- showing width/length size of a compartment grid cell
- similar dimension precalculation for the whole bin
- now there is an option to preserve inputs after creation (though they won't survive fusion restart)

**Comment by Le0Michine** [comment]
I'm gonna close it for now as it seems that current implementation seems to cover your use cases
