### ISSUE TITLE
Remove flats on bottom of bin profiles

### ISSUE THREAD

**Issue by lutorm** [Le0Michine/FusionGridfinityGenerator#83]
Currently it appears that the bottom pattern is generated by truncating the bottom pattern to 41.5mm, and then composing multiples of this by spacing them 42mm apart. This creates a 4.75mm high profile with a 0.5mm flat between the units. Because of the tolerance on the chamfered part of the pattern, a box with more than one unit will always sit on these flats, not on the chamfers. This causes a 2-wide bin to rock on the center flat.

In contrast, looking at Zack's "Parametric Divider Box" project, the bottom profile is 42mm wide and 5mm tall, so when composing units there is no flat section in the middle. Only the external parts of the profile are then truncated by the 0.25mm tolerance on each side. In my experience, these nest much more solidly.

See images, the top is generated by this tool and the bottom is from Zack's design:
![gridfinity_flat](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/5422104/31e18116-df44-4774-876e-2b8124e3e236)
![gridfinity_noflat](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/5422104/f02601f1-6505-4d34-ae39-64963b7c240f)

The fit of the bins would be improved if the flats between the units were eliminated and the chamfers met in the middle, like in Zack's design.

**Comment by muppy** [comment]
I had the same request :) it looks you anticipated me :)

**Comment by Le0Michine** [comment]
Hi, could you provide more details about the issue you are facing? From your description it doesn't sound like making those chamfers meet would really help as bin could just sit on a single line and still wobble. What baseplate model are you using and what is the ridge hight on it?

Just for the reference, this is where base height comes from https://gridfinity.xyz/specification/
<img width="181" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/2bdfae23-112f-48bc-84bc-7d351903f2b2">

**Comment by lutorm** [comment]
Here's the enlarged profile from that web site:
![profile](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/5422104/a1f9a742-ef80-4479-92af-0c0e4c616f24)
So think about what happens with a 1x1 bin. The image above creates an empty space all around the bin, but since it has to bear on something, it'll just fall down and rest on the chamfer. (In this way, clearancing the chamfers is sort of pointless, all that does is drop the bin further down. What's important is that the vertical sides have clearance because without that the bin won't sit in the baseplate at all.)

![profile2](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/5422104/be48b14f-a4aa-4970-b46b-c69ba00709cf)

Now think about what happens with a 1x2 bin. You'd mirror the profile across the baseplate centerline (indicated in red in the new picture above).  If you connect the two profiles with a flat section at the top of the chamfer like the plugin does now, like the blue line in the image, the bin can no longer drop down and sit on the chamfers like the 1x1 did. Instead, the flat section will rest on the point at the top of the baseplate. For the bin to rest on the chamfers like the 1x1 did, you have to extend the chamfers of the module until they meet above the top of the baseplate, as indicated by the orange line (and like they do in Zack's design in the lower picture I included in the OP).

Hope that makes it clearer.

**Comment by lutorm** [comment]
Incidentally, I tried deleting the face in F360 and it sort of works. For 1xN bins, the result seems fine. If there are several rows and columns, though, deleting the face results in a shell crossing at the intersection because the fillet in the intersection crosses the inner bottom of the bin. E.g. see below:
![section](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/5422104/454d88cd-fc8d-4865-b107-16c588b34ea1)
Making the bottom thicker would solve this but that doesn't appear to be an option.

**Comment by tache** [comment]
Yep - saw this and meant to post this as well. You an see it when you are in the slicer when it will ask for the supports, where the official does not. Also note Zach's bin is 0.43mm taller compared to a generated bin. It lust looks like it starts a bit early. 

Here is the comparison of a Zach bin to a generated bin. Zach on the left with the throw holes and a generated bin on the right. Also not the stability error with the generated bin. 

## Layer 23 
![issue-layer-23](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/144bc3b9-909d-4069-bdbc-08831baaee98)


## Layer 24 
![issue-layer-24](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/63d6dba6-e381-41ec-a967-e09287d42e6a)


## Layer 25 
![issue-layer-25](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/4170c513-6cca-417b-b7be-b2211172313d)


## Layer 26 
![issue-layer-26](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/6dcd96b4-6e52-4bec-90f2-502b6c68028c)


## Layer 27 
![issue-layer-27](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/3aa01f05-9577-49af-bcfa-58c8e1660789)

##Stability Error 
![error](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/594187/6b6dc02d-af76-4f27-bcca-2ff696876d12)

**Comment by lutorm** [comment]
So I realized this is only an issue if you use Zack's baseplate. The baseplates created by this add-in aren't pointy in the center, so there's no issue if you only use this add-in. The problem appears if you use these bins on the baseplates from e.g. https://thangs.com/designer/ZackFreedman/3d-model/Gridfinity%20Baseplates-60925.

It's kind of unfortunate to have two mutually incompatible designs, but as long as you use the add-in to create your baseplates you'll be fine using whatever bin designs, so it's not a huge deal.

**Comment by fneb** [comment]
Just wanted to chime in and say this is something I would appreciate too. I'm working on a design that is overall 6x4 Gridfinity units and has a bridge at the long ends within the grid and so bridges need to be in a specific direction. With this direction with the current implementation of this plugin results in bridges being attempted all the way down the 6 Gridfinity direction. 

Screenshot attached - the bridge I need is in the top-left area for reference, to show that I can't change the bridge direction for the whole model. Model in screenshot is entirely generated in Fusion 360 with this plugin being the only addon used. And since I'm designing this to be released for others to use I'd rather not need to give more printing instructions than needed. In the end I had to manually cut out sections from this base section and put chamfers in to resolve this.

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/5102354/377c28e3-2e83-407e-9f89-cefa85f0d86c)

**Comment by tache** [comment]
@Le0Michine Any update on this issue? Thoughts on when it could be completed? Is it a quick tweak of the layer generation parameters?

**Comment by fneb** [comment]
If it helps - either as part of developing a long-term fix option or for anyone reading this wanting a work-around - what I've found is the quickest way of doing this (with my limited CAD abilities) is to extrude the flat horizontal surface by -.25mm, then chamfer the whole surface. This will also put chamfers on this surface around the border of the bin, and if desired you can go around and delete these surfaces. In any case, I don't seem to be able to simply offset or move the surface up and have the chamfers meet that way.

**Comment by Le0Michine** [comment]
I took a stab at it, all I can say right now is that it is a work in progress and it does require reworking/rethinking how base is generated. It is not a straightforward change as base is used in a lot of different places such as cutting out stackable lip, generating lip notches, baseplate. And there are still quite a bit of unobvious assumptions and hardcoded consts left throughout the code since early days of the plugin. That's said I believe I found the solution and slowly making progress

<img width="1177" alt="image" src="https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/1a5a2a22-856a-448e-a5b1-5ccac956384b">

**Comment by fneb** [comment]
Thanks! I figured it would be complicated given that the face couldn't simply be offset. Much appreciated that you're working on this!

**Comment by tache** [comment]
So is this closed now? I see it generates correctly in the latest update.

**Comment by Le0Michine** [comment]
it's only available for installation from source code and hasn't been released yet, will resolve once release is prepared

**Comment by Le0Michine** [comment]
Addressed in v1.4.0.0

**Comment by tablatronix** [comment]
Just came to post that I prefer the .5 flats, and not this change,  it makes bins pinch or bind instead of slide over others, but considering bridging is worth looking at, although i never have an issue
