### ISSUE TITLE
Feature request: Lids

### ISSUE THREAD

**Issue by the-robo** [Le0Michine/FusionGridfinityGenerator#86]
Please add a Lid feature.

I can work around this missing feature by generating a solid body with no lip and no base.  However I would like a lid with the base all as a single unit. For example, if I create a bin (lid) with 1u width and 3u length and 1u height, no lip, and a base; I get a lid with a (3u) segmented base.

Options:
- Magnets; add pillars with a small indents in the top for magnets inside the box and matching indents in the lid. (use existing magnet options).
- Notches (small indents) in the side of the lid for ease of opening.
- Tabs on the side of the lid for ease of opening.
- Single unit base (as described above)
- Hinges; standard outer hinges. Print in place or separate.
- Hinges; hidden inner hinges (I am working in fusion on this and it is tricky!)
- View port; the lid is more or less a rim with an area to glue in clear plastic (PET, acrylic, etc.)

More ideas available on request. Email me or chat on Discord.

**Comment by t-makaro** [comment]
Duplicate of #53

**Comment by Le0Michine** [comment]
thanks @t-makaro , closing as duplicate
