### ISSUE TITLE
Label Tab Overhang Angle not preserved

### ISSUE THREAD

**Issue by t-makaro** [Le0Michine/FusionGridfinityGenerator#88]
I like to set the tab overhang angle to 60° since it saves filament, gives the bin more space, and my printer handles that angle without issue. But after creating the first bin (with preserve inputs enabled), when creating another bin the UI to generate a bin shows the wrong angle:
![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/18018386/7fda95a3-b86a-4c50-b6ad-a4a52bb6fc26)

Version: 1.2.7.0

**Comment by t-makaro** [comment]
I just checked. This seems to be fixed in v1.3.1.0.

**Comment by lutorm** [comment]
Cool. Is there a way to get a notification when a new version is released?

**Comment by Le0Michine** [comment]
> I just checked. This seems to be fixed in v1.3.1.0.

Thanks for confirming. It looks like there was a conversion issue between degrees and radians

**Comment by Le0Michine** [comment]
> Cool. Is there a way to get a notification when a new version is released?

Unfortunately not at the moment, fusion doesn't provide a nice way for checking for a new version so it would need to be implemented separately. The next best thing is to subscribe to the repository updates here on github which should include new release notifications among other things
