### ISSUE TITLE
Half Width Bins

### ISSUE THREAD

**Issue by sdsteve** [Le0Michine/FusionGridfinityGenerator#9]
This tool is amazing! One feature that would be awesome to have would be the ability to create half width bins.  I have been printing some of the half width bins that already exist but I would like to create custom sizes as well.  The tool allows the entry of the half width and creates the bin correctly, but the base does not scale down appropriately.

**Comment by sdsteve** [comment]
That works great!  I got one error but it was due to trying to add dividers in the wrong direction.  Thanks!!

**Comment by Le0Michine** [comment]
can you share a screenshot with the error and your inputs?

**Comment by sdsteve** [comment]
Sure.  Here are the pics I took before I realized my mistake.  FWIW - it's working great for everything I need it to do! Thanks again!

<img width="504" alt="Screenshot 2023-03-22 at 10 39 26 AM" src="https://user-images.githubusercontent.com/49568833/227001262-5a623af4-ea70-4970-b167-e1f64c4be193.png">
<img width="551" alt="Screenshot 2023-03-22 at 10 39 32 AM" src="https://user-images.githubusercontent.com/49568833/227001270-045b97ae-f117-4546-a848-3c5d8b6a9d96.png">

**Comment by Le0Michine** [comment]
thanks, looks like in that case I can add some highlighting for that particular error so it would be more obvious

![image](https://user-images.githubusercontent.com/2707008/227093907-22ae0f9e-272f-44a6-b94a-f056f1986f80.png)

**Comment by sdsteve** [comment]
Smart - I like it.  I would have figured out my error at least five minutes faster. :)

I have a completely separate question for you:

I have actually purchased all of the original bins designed by Alex Chappel that were the original idea behind Gridfinity.  One idea I had while I printed some custom Gridfinity Bins is maybe I could use your plugin to create a few custom bins to augment my larger bin collection.  

I've been playing with your script (which is super cool) and found that three parts would need to change: how the base of the bin is formed, how the cutouts in the bin ledge of the bins are formed, and the shapes used to create the base plates.  I'm doodling with the python a little, but if you're interested in that as a feature for the entire fork - I just thought I would mention it.  Obviously your python skills are far beyond my own.

**Comment by Le0Michine** [comment]
If I understand your question correctly you want to be able to generate bins for ALCH format right? that might potentially be possible and I'm pretty sure just changing base shape would get you close enough as it is used for basepates as well as for the bin ledge at the top of the bin. There are might be some annoying difficulties like the corner fillet being a fixed const and probably some calculations are making assumptions around how the result should look like for instance origin of most elements isn't flexible. But I'm not sure if that would be possible to easily incorporate into the addin for couple reasons
- potential licensing issue, Alex sells his creation and doesn't (to my knowledge and maybe nobody asked him) allow free distribution even if that wouldn't be technically the same files
- that would require a substantial amount of refactoring, I'm just not ready for it at the moment, I'm trying to improve the code little by little, but I'm not sure how much time it would take. PRs are always welcome, however they also take time to merge especially for a project with no tests
