### ISSUE TITLE
It freezes when generating bins with these settings

### ISSUE THREAD

**Issue by pupeno** [Le0Michine/FusionGridfinityGenerator#98]
With the bin length of 3 it worked well, with 5 it took a while but it generated the bin, maybe a minute. With bin length 8 it's just frozen. If it's ever going to finish, the time complexity feels exponential or higher. Could it be something triggered by making the bin size 12mm by 12mm? Or shelled?

![Screenshot 2024-04-28 073400](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/8425/b9c5f212-3050-44d4-9d3d-09dfd4b4560f)

**Comment by pupeno** [comment]
I think the the problem is triggered by the shelled instead of hollow option.

**Comment by Le0Michine** [comment]
I'll try to reproduce. Just wondering, are you doing that with base magnet sockets/screw holes enabled or disabled? 
Asking because that could be the source of square-ish complexity for pattern feature, screw holes are created as pattern of 4 elements and then base tiles would be generated as another pattern feature including the previous one inside it. I hope it's something else though, but can't think of anything else right now

**Comment by pupeno** [comment]
No magnets or screw holes:

![Screenshot 2024-05-05 094926](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/8425/6d09225f-b449-45dd-a9f1-12f73f40f1c5)

**Comment by pupeno** [comment]
This is what it looks like when it gets frozen:

![Screenshot 2024-05-05 095020](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/8425/2ed665d1-c268-4252-9e29-cc95b9b34fc4)

**Comment by Le0Michine** [comment]
tried to reproduce, I can see that "shelled" option takes slightly longer comparing to "hollow", but it still succeeds for me within a few seconds. When I increase the size up to 10 by 10 it takes about 6-7 seconds for "hollow" and ~13 seconds for shelled version which is almost 2 times difference. I wonder if using "hollow" option would be able compute in your environment or if it would also freeze

**Comment by pupeno** [comment]
Hollow works, it's only shelled that gets stuck, and I have let it running for a few minutes. The CPU I'm running on is a Intel Core i7-6850K 3.6 GHz, and the graphics card is a nVidia GeForce RTX 3090.

**Comment by Le0Michine** [comment]
I was trying it on an m3, will give it a try on a windows machine when I get a chance. To my knowledge fusion neither takes advantage of multi core nor does it use gpu for model computations.

I suspect the only way to resolve this is to implement shell feature manually by building and subtracting inner volumes

**Comment by Le0Michine** [comment]
tried it on Win 11, with Ryzen 5 3600x (I think it's 4.4 GHz), it didn't freeze while generating this 10x10 shelled bin, took a bit longer, just under 25 seconds.

![image](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/2707008/79fc8988-5b0f-4a5d-a35d-61e5396c9a49)

**Comment by pupeno** [comment]
I'm running on Windows 10, I doubt that makes a difference though.

**Comment by pupeno** [comment]
Is there anything I can do to help debug this? And if not, if it's not reproduceable, I think just closing it is ok.

**Comment by Le0Michine** [comment]
you could try to generate solid bin and apply shell operation manually to it to see if it would get stuck as well

**Comment by pupeno** [comment]
Since I posted this bug, I upgraded my computer to a better CPU, motherboard, and RAM, but also I'm running on a fresh Win 11 install. Now I can't reproduce it anymore. Unfortunately, I'm not sure what fixed it of all the changes. It's much faster now than what the CPU upgrade would indicate, so I think it's not a matter of performance. Maybe the clean install solved a problem.
