### ISSUE TITLE
42mm used for the display size instead of the based width and length

### ISSUE THREAD

**Issue by pupeno** [Le0Michine/FusionGridfinityGenerator#99]
I think when calculating the size being shown in the form, it's using a hard-coded 42mm instead of the entered details.

![Screenshot 2024-04-28 074336](https://github.com/Le0Michine/FusionGridfinityGenerator/assets/8425/2e0fff10-9809-4c9f-ad96-01985829b2eb)

**Comment by Le0Michine** [comment]
thanks for reporting this, that's a good find, will check the code later to confirm

**Comment by Le0Michine** [comment]
Fixed in v1.4.0.0
